#!/bin/sh

# SERVER will be accessed via ssh/dbclient. Highly recommend setting up passwordless
# authentication prior to use here.
SERVER=server1359.seedhost.eu
DESTBASE="/home/chjones"

# limit bandwidth to this number of kilobytes per second
KBPS=4096

# Where to find the necessary programs
SSH=/bin/dbclient # should be compatible with basic ssh
NICE=/bin/nice
IONICE=/bin/ionice
RSYNC=/bin/rsync

# Commands with their options, without arguments
# These will be used unquoted; escape as needed
SSHCMD="$SSH"
IONICECMD="$IONICE -c 3"
NICECMD="$NICE -n 10"
RSYNCCMD="$RSYNC -rlptP -bwlimit $KBPS -e $SSH"
UPLOADCMD="$IONICECMD $NICECMD $RSYNCCMD"

usage() {
	echo "Usage: $0 [-hqv] [path] [path...]"
}

VERBOSE="N"
while [ "${1#-}" != "$1" ]; do
	for opt in $(echo "${1#-}" | sed -E 's/(.)/\1 /g'); do
		case "$opt" in
		"v")
			VERBOSE="Y"
			UPLOAD="$UPLOAD -v"
			;;
		"q")
			VERBOSE="N"
			;;
		"h")
			usage
			exit 0
			;;
		"" | " ") ;;
		*)
			echo "Unknown option: ${opt}" >&2
			usage >&2
			exit 1
			;;
		esac
	done
	shift
done
if [ "$VERBOSE" == "N" ]; then
	UPLOAD="$UPLOAD -q"
fi

for path in "$@"; do
	if [ ! -r "$path" ]; then
		echo "Unable to access $path" >&2
		usage >&2
		exit 1
	fi
done

for path in "$@"; do
	case "$path" in
	*/Movies | */Movies/)
		if [ "${path%/}" == "${path}" ]; then
			path="$path"/
		fi
		DESTDIR="$DESTBASE/Media/Video/Movies"
		;;
	*/TV | */TV/)
		if [ "${path%/}" == "${path}" ]; then
			path="$path"/
		fi
		DESTDIR="$DESTBASE/Media/Video/TV"
		;;
	*)
		while [ "${path%/}" != "$path" ]; do
			path="${path%/}"
		done
		DESTDIR="$DESTBASE/downloads"
		;;
	esac
	if [ "$VERBOSE" == "Y" ]; then
		echo "Uploading $path to $SERVER:$DESTDIR"
	fi
	$UPLOAD "${path}" "${SERVER}:${DESTDIR}"
done
